/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#002113',
        'inverse-primary': '#c3c0ff',
        'on-background': '#131b2e',
        background: '#faf8ff',
        'on-primary': '#ffffff',
        secondary: '#006c49',
        'surface-dim': '#d2d9f4',
        'secondary-fixed': '#6ffbbe',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#653e00',
        'error-container': '#ffdad6',
        'on-surface-variant': '#464555',
        'primary-fixed-dim': '#c3c0ff',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#005236',
        'primary-container': '#4f46e5',
        'surface-container-highest': '#dae2fd',
        'on-secondary-container': '#00714d',
        'secondary-fixed-dim': '#4edea3',
        'primary-fixed': '#e2dfff',
        'surface-container-low': '#f2f3ff',
        surface: '#faf8ff',
        tertiary: '#684000',
        outline: '#777587',
        primary: '#3525cd',
        'outline-variant': '#c7c4d8',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary': '#ffffff',
        'surface-container': '#eaedff',
        'on-tertiary-container': '#ffd4a4',
        error: '#ba1a1a',
        'on-surface': '#131b2e',
        'tertiary-fixed': '#ffddb8',
        'on-primary-container': '#dad7ff',
        'surface-variant': '#dae2fd',
        'secondary-container': '#6cf8bb',
        'tertiary-container': '#885500',
        'on-tertiary-fixed': '#2a1700',
        'surface-bright': '#faf8ff',
        'inverse-surface': '#283044',
        'on-primary-fixed': '#0f0069',
        'surface-container-high': '#e2e7ff',
        'inverse-on-surface': '#eef0ff',
        'on-secondary': '#ffffff',
        'surface-tint': '#4d44e3',
        'on-primary-fixed-variant': '#3323cc',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-xl': '2rem',
        'margin-tablet': '1.5rem',
        'gutter-tablet': '1.25rem',
        gutter: '1rem',
        'margin-desktop': '2.5rem',
        'space-sm': '0.5rem',
        'space-lg': '1.25rem',
        'space-md': '0.75rem',
        'gutter-desktop': '1.5rem',
        margin: '1rem',
      },
      fontFamily: {
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Inter"', 'sans-serif'],
        'body-lg': ['"Inter"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Inter"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-hero': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-hero-mobile': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
